### ISSUE TITLE
Problem with afterScript when running with AWS Batch

### ISSUE THREAD

**Issue by toniher** [biocorecrg/vectorQC#11]
It seems to fail in trimmedQC step

https://github.com/biocorecrg/vectorQC/blob/master/main.nf#L173

**Comment by lucacozzuto** [comment]
This not a problem of afterScript. It was an error with the definition of the output file. Fixed here https://github.com/biocorecrg/vectorQC/commit/87915b0feedd6e149764c6f35499de30d60545cd
