### ISSUE TITLE
Problem with @ parameter at runRestrict in AWS Batch

### ISSUE THREAD

**Issue by toniher** [biocorecrg/vectorQC#12]
It seems that AWS Batch does not like @ character for file commonenz parameter.
Option to convert file into comma separated string list.

https://github.com/biocorecrg/vectorQC/blob/master/main.nf#L328

**Comment by lucacozzuto** [comment]
It looks like AWS doesn't like path. So I staged in the file in the nextflow working directory. Fixed in https://github.com/biocorecrg/vectorQC/commit/fa15fe55e62be0d90a00515eeff99c6667217d8f
