### ISSUE TITLE
Problem with multiQC report finding config.yaml in AWS Batch

### ISSUE THREAD

**Issue by toniher** [biocorecrg/vectorQC#13]
AWS Batch does not seem to find config.yaml. It seems to be a problem with the reporter function:

https://github.com/biocorecrg/vectorQC/blob/master/main.nf#L445-L446

```
Command exit status:
  1

Command output:
  (empty)

Command error:
  cat: /home/ec2-user/git/vectorQC/config.yaml: No such file or directory
```

**Comment by lucacozzuto** [comment]
No way to solve this. It looks a non compatibility between MultiQC, yaml-file glob and s3 environment
